### PR TITLE
critical bug fix - fixed rebaseRelativeTo with local vs url paths

### PR DESCRIPTION
**Pull request by niftylettuce**
Please merge!  This fixes an issue where you specify a local file system `relativeTo` option which causes path issue with `rebaseRelativeTo` and URL's such as `http://localhost:3000/img/foo.svg` becomes `http:/localhost:3000/img/foo.svg` (note the missing `//` in `http:/localhost` due to `path.resolve`.

All tests still pass and this fix can be merged.  I also bumped deps as well which closes #50 

Once you merge and release new version to npm please let me know 👍 

Many thanks as always Jarrett! @jrit 🙏 🎉

### CODE REVIEW

**Comment by niftylettuce** [comment]
All good to merge now and release!

**Review by jrit — APPROVED** [review]
LGTM, thanks!

**Comment by niftylettuce** [comment]
@jrit thanks! can you version bump `package.json` and release to npm?  also if you want help maintaining all this stuff I'd be glad to.

**Comment by jrit** [comment]
just published. I'm going to publish a new version of juice in a bit to close the node version compat issue that is still open there. Thanks for the offer, the volume of issues/PRs recently is really low so it isn't a lot of work but I can add you to one or both projects if you are wanting to work on things more actively.

**Comment by niftylettuce** [comment]
You rock dude.  Many thanks.  I was just suggesting to add me as a collaborator if you got too busy or whatever.  I'd gladly help maintain if you feel like it's too much on your plate.  I know I have a lot of projects going on myself but at the least it's a good measure to not have a single point of failure haha.  Thanks again dude.

**Pull request merged**
