### PR TITLE
De-Duplicating Global Regex Replacements for Rebasing

### LINKED ISSUE #2: Identical URLs in CSS File Rebase Incorrectly
In `css.js`, there is a loop:

``` js
while( ( found = urlRegex.exec( result ) ) !== null )
    {
        if( !found[ 0 ].match( new RegExp( "\\/\\*\\s?" + settings.inlineAttribute + "-ignore\\s?\\*\\/", "gi" ) )
            && ( settings.images || found[ 0 ].match( new RegExp( "\\/\\*\\s?" + settings.inlineAttribute + "\\s?\\*\\/", "gi" ) ) ) )
        {
            tasks.push( replaceUrl.bind(
            {
                src: found[ 1 ],
                limit: settings.images
            } ) );
        }
    }
```

Because your are doing regex replaces (rebasing) at the same time that you are finding `url()` references, and your regex replaces a global, if there are two identical `url()` references, the second one will not be rebased correctly.

For example:

``` css
url("../img/blah.png")
url("../img/blah.png")
```

Rebased to `xyz` would create:

``` css
url("img/blah.png")
url("xyz/img/blah.png")
```

Perhaps a better way to do this would be to loop through the document and find matches, assign those to an array to de-dup them, and then do a global regexp replace for each one in sequence.

I'm not saying this is a typical situation, but I did run into it.  In case you're wondering what I'm doing, I'm using Juice (which uses this package) to do automatic processing of ebook files that were generated by InDesign.  The CSS that ID generates is rather repetitive and includes multiple identical `url()` references, and the rebasing behavior of `web-resource-inliner` was making Juice explode on me.

### PR DESCRIPTION
**Pull request by tooolbox**
Fixes #2 

Sorry, took me a while :)

### CODE REVIEW

**Comment by jrit** [comment]
Awesome, thanks. Would you mind adding a test case to prevent regressions?

**Comment by tooolbox** [comment]
Oooooh, asking a lot...  ;)

I'll see what I can do.

**Comment by tooolbox** [comment]
Okay, so I spent over an hour trying to make this test case, and didn't manage to reproduce the exact scenario.  I'm not interested in diving into the Juice codebase and understanding what it's doing, and I can't spend any more time on this.

Perhaps you'll have better luck setting up a test case, but in either case this PR does fix the problem.

**Comment by jrit** [comment]
Thanks for the effort, I'll go ahead and merge but probably won't publish a release until I get a test added.

**Pull request merged**
