### PR TITLE
Fixed data URI detection, closes #28

### LINKED ISSUE #28: Detect if string is already Data URI (and if so then return early)
This is related to the issue I filed here <https://github.com/data-uri/datauri/issues/21> on the `data-uri` package.  I will be submitting a PR here that will alleviate the issue until it is fixed in `data-uri`.

### PR DESCRIPTION
**Pull request by niftylettuce**
Related to #28

### CODE REVIEW

**Comment by jrit** [comment]
This looks good to me, thank you. Would you mind adding a test case to prevent any future regression on this change? As you noted, at some point we'd hope this get's rolled into data-uri, so I'd like then to be able to make that dep upgrade and see the test still pass locally.

**Comment by niftylettuce** [comment]
I can try, my time is super limited atm tho

**Comment by tommedema** [comment]
Since this was stalled for 5 months I created a new PR with test case at #31

**Comment by jrit** [comment]
closing as resolved in #31

**Pull request closed without merging**
