### PR TITLE
rebaseRelativeTo fixes

### PR DESCRIPTION
**Pull request by seyfert**
Found two issues while trying to use the rebaseRelativeTo option on a CSS file.

1. Even though `rebaseRelativeTo` was set as an option, it wasn't being used.  It was always being overwritten by a path based on the `relativeTo` option.  Changed logic to use options value if it is defined.
2. The regular expression used to find/replace instances of url() with the new url based on the `rebaseRelativeTo` only allowed one url() per line and the url had to end with a semi-colon. But it is valid for a font-face url() to appear multiple times on the same line and not end with a semi-colon.  See [this article](https://css-tricks.com/snippets/css/using-font-face/).  In order to make this work I changed the regular expression to ignore the semi-colon, not do a global search, and set each subsequent search to start from the previous index+1.

All tests pass.

### CODE REVIEW

**Comment by jrit** [comment]
Awesome, thank you! Is there any way you can update or add test cases to prevent any future regressions related to your fixes?

**Comment by seyfert** [comment]
Sure.  I'll try to add tests for rebaseRelativeTo in the next few days.

**Comment by seyfert** [comment]
I found another issue while testing. The util function getInlineFilePath did not support fragment URLs.  I fixed that and added two additional tests that cover all the changes.

**Comment by jrit** [comment]
This looks great, thank you. I'll work on publishing a release today.

**Pull request merged**
